using System;
using System.Collections;
using System.Collections.Generic;
using InputLibrary;
using OutputLibrary;
using ValidationLibrary;

namespace EulerProblems
{
    public class Euler02
    {
        private int[] Results { get; set; }

        private string Title { get; set; }
        private List<string> Description { get; set; }
        private string[] EulerInstructions { get; set; }

        public Euler02()
        {
            Results = new int[] { 0, 0 };

            Title = "Even Fibonacci Numbers";

            Description = new List<string>{
                "Each new term in the Fibonacci sequence is generated by adding the previous two terms.",
                "By starting with 1 and 2, the first 10 terms will be:",
                "",
                "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...",
                "",
                "By considering the terms in the Fibonacci sequence whose values do not exceed four million,",
                "find the sum of the even-valued terms."
            };
        }

        public void EulerMain()
        {
            DisplayInstructions();
            string UserInput = QueryUser();
            int MaxRange = int.Parse(UserInput);

            int[] IntResults = new int[]{
                CalculateIterative(MaxRange),
                CalculateEfficient(MaxRange)};

            OutputService.ConvertToString(IntResults);
        }

        private void DisplayInstructions()
        {
            Description.ForEach(delegate(String item)
            {
                Console.WriteLine(item);
            });
        }

        private string QueryUser()
        {
            string[] EulerInstructions = new string[]{
                "Let's solve Euler # 2!",
                Environment.NewLine, Environment.NewLine,
                "Enter a maximum range value: "};

            return ValidationService.ValidateUserInput(EulerInstructions);
        }

        private int CalculateIterative(int maxRange)
        {
            int SumTotal = 0;
            int[] FibSet = new int[2] { 1, 2 };
            int Temp;
            while (LimitHasNotBeenReached(maxRange, FibSet[1]))
            {
                if (IsNumberEven(FibSet[1]))
                {
                    SumTotal += FibSet[1];
                }

                Temp = FibSet[1];
                FibSet[1] = FibSet[0]+ FibSet[1];
                FibSet[0] = Temp;
            }
            return SumTotal;
        }

        private bool LimitHasNotBeenReached(int maxRange, int current)
        {
            return current < maxRange;
        }

        private int CalculateEfficient(int maxRange)
        {
            int SeqNum = 2;
            int SeqSum = 0;

            while (SeqNum < maxRange)
            {
                SeqSum += SeqNum;
                SeqNum = GetValue(SeqNum);
            }
            return SeqSum;
        }

        private static int GetValue(int value)
        {
            return (int)Math.Round(value * 4.236068);
        } 

        private bool IsNumberEven(int fibOne)
        {
            return fibOne % 2 == 0;
        }
    }
}
